services:
  backend:
    image: ahmedkhamis10/shophoria_backend:1.3
    ports:
      - "3000:3000"
    env_file:
      - .env  # Backend reads from .env file
    environment:
      - AI_API_URL=http://ai:8000  # Set AI service URL directly in the environment
    depends_on:
      - db
      - ai  # The backend depends on the AI service

    container_name: backend

  ai:
    image: ahmedkhamis10/gp-ai1:latest  # AI service image
    ports:
      - "8000:8000"  # Expose AI service on port 8000

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  apache:
    image: httpd:2.4
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./httpd/proxy.conf:/usr/local/apache2/conf/extra/proxy.conf:ro
    command: >
      bash -c "echo 'Include conf/extra/proxy.conf' >> /usr/local/apache2/conf/httpd.conf && httpd-foreground"
    depends_on:
      - backend

volumes:
  postgres_data: