require('dotenv').config();

const { PORT , DB_HOST , DB_PORT , DB_USER , DB_PASSWORD , DB_DATABASE , HASH_SALT_ROUNDS ,AI_API_URL,
        PAYMOB_FRAMEID_1,PAYMOB_FRAMEID_2,PAYMOB_API_KEY,
        PAYMOB_INTEGRATION_ID_1,PAYMOB_INTEGRATION_ID_2,URL_GET_AUTH_TOKEN,URL_REG_ORDER_ID,URL_GET_PAYMENT_KEY
    } = process.env;

module.exports = { PORT , DB_HOST , DB_PORT , DB_USER , DB_PASSWORD , DB_DATABASE , HASH_SALT_ROUNDS,AI_API_URL,
            PAYMOB_FRAMEID_1,PAYMOB_FRAMEID_2,PAYMOB_API_KEY,
        PAYMOB_INTEGRATION_ID_1,PAYMOB_INTEGRATION_ID_2,URL_GET_AUTH_TOKEN,URL_REG_ORDER_ID,URL_GET_PAYMENT_KEY
};